baseURL = 'https://warski.org/'
languageCode = 'en-us'
title = "Adam Warski: programming articles & videos"
author = "Adam Warski"
name = "Adam Warski"
summarylength = 15
[services]
  [services.disqus]
    shortname = 'warski'

[params]
  description = "Architecture, distributed systems, functional programming, event sourcing, developer experience & more."

[[params.plugins.js]]
  link = "js/tab.js"
[[params.plugins.js]]
  link = "plugins/youtube-lite.js"

[markup.goldmark.renderer]
unsafe= true

# Menus
[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
[[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 40
[[menus.main]]
    name = 'Articles'
    pageRef = '/articles'
    weight = 50
[[menus.main]]
    name = 'Videos'
    pageRef = '/videos'
    weight = 60
[[menus.main]]
    name = 'Talks'
    pageRef = '/talks'
    weight = 70
[[menus.footer]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.footer]]
    name = 'About'
    pageRef = '/about'
    weight = 20
[[menus.footer]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 40
[[menus.footer]]
    name = 'Articles'
    pageRef = '/articles'
    weight = 50
[[menus.footer]]
    name = 'Videos'
    pageRef = '/videos'
    weight = 60
[[menus.footer]]
    name = 'Talks'
    pageRef = '/talks'
    weight = 70
